### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by DocCyblade** [MPTMG/Mumble#1]
[In the .art folder](https://github.com/MPTMG/Mumble/tree/master/.art):

You can remove the default core screen shots and add you own. [Instructions to do so can be found here](https://github.com/turnkeylinux/artwork/blob/master/docs/screenshots.rst)

I am going through your code top down, that why I started with the art work :-)

**Comment by MPTMG** [comment]
Thanks. Will remove the default artwork and add my own. Thanks for links to relevant information by the way it helps in correcting the flaws quickly.

**Comment by DocCyblade** [comment]
No problem, I have gotten help from @JedMeister when building new apps, and I am following his lead. He always tries to link thinks when he posts, and I agree it does help! Jeremy is off this week for some well deserved R&R, or you would normally be hearing from him. Since he was off this week I thought I would step in and try to help where I can. He would be the one who forks your repo and pulls it into the official TKL repo.

**Comment by MPTMG** [comment]
Updated per suggestion. Take a look and provide feedback if further changes are needed.

**Comment by JedMeister** [comment]
Your icon loos awesome, good work on that. 

However, (and sorry about this), but it looks like all your all your screenies and your icon have white background (rather than transparent). On our current website it doesn't really matter (as we use a white background) but that may not always be the case. Actually we are well overdue for an update/refresh...

Also if you still have the xcf files (from gimp), please include them too. It's not the historical convention (I don't think any of the other appliances have them) but it's a new convention I'd like to introduce as it makes it much easier for future updates and tweaks to icons and screenshots.

**Comment by MPTMG** [comment]
I have the xcf, must have missed an option when exporting from gimp on transparent background . I will include the xcf and update the others to transparent backgrounds. Oh and you don't have to be "sorry" about anything. If it needs to be fixed, it needs to be fixed. I have never claimed perfection and as with any "work" there are numerous ways to get the job done. If I ever disagree with a comment I will make my case for my way. If my case is not strong enough to convince others I will take their suggestions and incorporate them.

**Comment by DocCyblade** [comment]
@JedMeister - I like the idea of of including the gimp file. TBH I don't know if I still have the ones for mayan, and I just did them!  Your thoughts on that from the TKL perspective?

**Comment by MPTMG** [comment]
Artwork updated. Close when you guys are satisfied with the results.
