### ISSUE TITLE
Create your own config files for apache

### ISSUE THREAD

**Issue by DocCyblade** [MPTMG/Mumble#5]
I would [not use the default web site configs](https://github.com/MPTMG/Mumble/tree/master/overlay/etc/apache2/sites-available), and use your own. [I see on your confconsole ](https://github.com/MPTMG/Mumble/blob/master/overlay/etc/confconsole/services.txt) that port 80 will be the standard web console, and 443 will be used the mumble console. I would create one file for each, one for the web console and one for the mumble console. This way some like my self disable the default web console for security, and having them in two files I can easy disable it.

**Comment by MPTMG** [comment]
Config files have been created separate from defaults. I created MyMumb.conf and tk-webcp.conf and then enabled them in conf.d/main. Hence now you can just disable one of them and only have the mumble console available per your suggestion. In addition to these changes I moved the confconsole stuff to a folder (tk-webcp) in /var/www/ in the overlay. Due to the way the common overlay for tk-webcp places files I also had to move some files via conf.d/main. You should see this in the next commit after I test to make sure the details integrated from common work as expected.

**Comment by MPTMG** [comment]
Latest commit has integrated this best practice.

**Comment by DocCyblade** [comment]
Looks good this can be closed 👍
